name: "Publish to Dynamis"
description: "Publish a new version of a plugin to Dynamis"

inputs:
    plugin_id:
        description: "The plugin ID in Dynamis"
        required: true
    internal_name:
        description: "The internal name of the plugin in Dynamis"
        required: true
    path:
        description: "The path to the plugin zip file"
        required: true
    type:
        description: "The type of version; `latest` or `testing`"
        default: "testing"

runs:
    using: "node20"
    main: "dist/index.js"
